# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "This lane test the app"
  lane :test do
    run_tests
  end

  desc "This lane build the app"
  lane :build do
    gym
    #build_app(export_xcargs: "-allowProvisioningUpdates")
  end

  lane :refreshJenkinsKeychain do
    delete_keychain(name: "jenkins") if File.exists? File.expand_path("~/Library/Keychains/jenkins-db")
    create_keychain(
      name: "jenkins",
      password: "jenkins",
      timeout: false,
      lock_when_sleeps: false,
      unlock: true
    )
  end
end
